version: "3.7"

services:
    frontend:
        container_name: 'frontend'
        image: wmsfrontend
        build:
            context: '.'
            dockerfile: client.dockerfile
        ports:
            - 4200:80
        #restart: on-failure
        #healthcheck:
        #    test: "exit 0"
        networks:
            - wmsnetwork
    appide:
        image: 'wms-ide'
        build:
            context: '.'
            dockerfile: Dockerfile
        ports:
            - 5001:5001
        environment: 
                - ASPNETCORE_ENVIRONMENT=linux
                - ASPNETCORE_URLS=http://+:5001
                - MapServerHost=localhost
                - ProxyToPort:80
                - AllowedUrls="mapserv","appgiswms","authenticate"
                - SessionToken="Auth-"
                - CookieToken="WMS.Auth= "
                - SetCookie="set-cookie"
                - CacheControlMaxAgeInASeconds=86400
                - ConnectionStrings__UsersDatabase=host=pgdb;port=5432;database=publicgis;user id=docker;password=docker;
        expose:
            - 5001/tcp
        networks:
            - wmsnetwork
networks:
  wmsnetwork:
     driver: bridge